# Generated by Django 4.2.5 on 2023-11-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Middle', 'Middle'), ('Low', 'Low')], default='High', max_length=7, verbose_name='Priority')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], default='In progress', max_length=12, verbose_name='Status')),
                ('completed_at', models.DateTimeField(verbose_name='Completed')),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Image')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
        ),
    ]
