# Generated by Django 4.2.5 on 2023-11-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(null=True, verbose_name='Completed'),
        ),
    ]
